# -*- coding: utf-8 -*-
"""논프 숙제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KC_YLdtwfoTWs5HvgxJKUxXhQ4CAeD5u

# 10/10 과제
"""

### 1. 5개의 정수를 입력받고, 입력받은 숫자 중에  2번째로 높은 숫자를 출력합니다. 코드를 완성후 잘 작동하는 지를 알 수 있는 결과도 보내주세요.

a = int(input("첫번째 정수를 입력하세요."))
b = int(input("두번째 정수를 입력하세요."))
c = int(input("세번째 정수를 입력하세요."))
d = int(input("네번째 정수를 입력하세요."))
e = int(input("다섯번째 정수를 입력하세요."))

box = [a, b, c, d, e]
box.sort()
box.reverse()

print("두번째로 높은 숫자는:4", box[1])

# 2. 두개의 숫자를 입력받으면 그 중 큰 값을 출력하는 함수(function)을 만듭니다
#  이제 두 개의 숫자를 입력받고 그 함수를 불러와서 큰 수를 찾고, 그 큰 수가  1이상 10이하이라면 그 숫자의 갯수만큼 별표 *를 찍어주세요.
#  만약의 큰수가  1이상 10이하 밖의 범위라면, 1이상 10이하의 숫자를 입력해 달라는 메세지가 나오도록 해주세요.

def print_stars_for_larger_number():
    num1 = int(input("첫 번째 숫자를 입력하세요: "))
    num2 = int(input("두 번째 숫자를 입력하세요: "))

    if num1 > num2:
        larger_number = num1
    elif num2 > num1:
        larger_number = num2
    else:
        print("두 숫자는 같습니다.")
        return

    if 1 <= larger_number <= 10:
        print("*" * larger_number)
    else:
        print("1 이상 10 이하의 숫자를 입력해주세요.")

print_stars_for_larger_number()